<a href='<?=hlien('agence', 'liste')?>'>agence</a>
<a href='<?=hlien('categorie', 'liste')?>'>categorie</a>
<a href='<?=hlien('choisir', 'liste')?>'>choisir</a>
<a href='<?=hlien('departement', 'liste')?>'>departement</a>
<a href='<?=hlien('intervalle', 'liste')?>'>intervalle</a>
<a href='<?=hlien('locations', 'liste')?>'>locations</a>
<a href='<?=hlien('options', 'liste')?>'>options</a>
<a href='<?=hlien('profil', 'liste')?>'>profil</a>
<a href='<?=hlien('tarif', 'liste')?>'>tarif</a>
<a href='<?=hlien('utilisateur', 'liste')?>'>utilisateur</a>
<a href='<?=hlien('voiture', 'liste')?>'>voiture</a>
